# Generated by Django 4.2.6 on 2023-10-31 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="Category",
            new_name="category",
        ),
    ]
